name: untitled
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  dots_indicator: ^2.1.0
  shared_preferences: ^2.0.11
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true


  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Black.ttf
           weight: 400
         - asset: assets/fonts/Roboto-Bold.ttf
           weight: 500
         - asset: assets/fonts/Roboto-Medium.ttf
           weight: 700
         - asset: assets/fonts/Roboto-Regular.ttf
           weight: 900
  #
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
